//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_Register
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentInformation
    {
        public int Id { get; set; }
        public string StudentName { get; set; }
        public string Roll { get; set; }
        public string Class { get; set; }
        public string Section { get; set; }
        public string Age { get; set; }
        public string AddedBy { get; set; }
    }
}
